In [47]:
import pandas as pd
import numpy as np

In [48]:
df = pd.read_csv('covid_toy.csv')

In [49]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

Doing it hard way

In [50]:
from sklearn.impute import SimpleImputer

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [54]:
from sklearn.preprocessing import OrdinalEncoder

In [55]:
df.age

0     60
1     27
2     42
3     31
4     65
      ..
95    12
96    51
97    20
98     5
99    10
Name: age, Length: 100, dtype: int64

In [56]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [57]:
df.cough.value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [60]:
df.fever.isnull().sum()

np.int64(10)

In [58]:
df.city.value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split

In [61]:
x_train, x_test , y_train , y_test = train_test_split(df.drop(columns= ['has_covid']) , df.has_covid , test_size = 0.2)

In [62]:
x_train

age  gender  fever   cough       city
63   10    Male  100.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
83   17  Female  104.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
51   11  Female  100.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
43   22  Female   99.0    Mild  Bangalore
35   82  Female  102.0  Strong  Bangalore
93   27    Male  100.0    Mild    Kolkata
9    64  Female  101.0    Mild      Delhi
21   73    Male   98.0    Mild  Bangalore

[80 rows x 5 columns]

In [68]:
df.fever.isnull().sum()

np.int64(10)

As fever column has missing values, we selected the fever column from train data and applied simple imputer, same with test data.

In [63]:
si = SimpleImputer()

In [64]:
x_train_fever = si.fit_transform(x_train[['fever']])

In [65]:
x_train_fever

array([[100.        ],
       [100.        ],
       [104.        ],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [100.88888889],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [100.88888889],
       [101.        ],
       [101.        ],
       [103.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [ 99.        ],
       [100.88888889],
       [100.        ],
       [101.        ],
       [102.        ],
       [100.88888889],
       [103

In [66]:
x_test_fever = si.fit_transform(x_test[['fever']])

In [67]:
x_test_fever

array([[101.        ],
       [100.66666667],
       [100.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [103.        ],
       [100.66666667],
       [104.        ],
       [ 98.        ]])

For the cough column - the values can have rank (generally strong > mild), we selected train data and applied ordinal encoder and same with test data. 

In [69]:
oe = OrdinalEncoder()

In [70]:
x_train_cough = oe.fit_transform(x_train[['cough']])

In [71]:
x_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [72]:
x_test_cough = oe.fit_transform(x_test[['cough']])

In [73]:
x_test_cough

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.]])

For city and gender column , that has nominal categorical data (no possible rank), we selected each column from train and test data, applied One Hot encoder.   

In [74]:
ohe = OneHotEncoder()

In [75]:
x_train_city = ohe.fit_transform(x_train[['city']])

In [76]:
x_train_city

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 80 stored elements and shape (80, 4)>

In [77]:
x_train_gender = ohe.fit_transform(x_train[['gender']])

In [78]:
x_train_gender

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 80 stored elements and shape (80, 2)>

In [79]:
x_test_city = ohe.fit_transform(x_test[['city']])

In [80]:
x_test_city

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20 stored elements and shape (20, 4)>

In [81]:
x_test_gender = ohe.fit_transform(x_test[['gender']])

In [82]:
x_test_gender

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20 stored elements and shape (20, 2)>

The above code for city and gender can create the MULTICOLINEARITY problem, to solve it we can drop the first column from each.

In [85]:
ohe = OneHotEncoder(drop='first' , sparse_output=False)

In [86]:
x_train_city = ohe.fit_transform(x_train[['city']])

In [87]:
x_train_city

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0

In [89]:
x_test_city = ohe.fit_transform(x_test[['city']])

In [90]:
x_train_gender = ohe.fit_transform(x_train[['gender']])

In [91]:
x_test_gender = ohe.fit_transform(x_test[['gender']])

In [92]:
x_test_city

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [93]:
x_train_gender

array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [94]:
x_test_gender

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

To concat all the columns, we need to extract the age column    

In [97]:
x_train_age = x_train.drop(columns = ['gender','fever','cough','city']).values

In [98]:
x_train_age

array([[10],
       [55],
       [17],
       [44],
       [11],
       [65],
       [75],
       [ 5],
       [34],
       [ 5],
       [47],
       [48],
       [25],
       [49],
       [16],
       [12],
       [25],
       [20],
       [42],
       [49],
       [15],
       [65],
       [60],
       [81],
       [84],
       [66],
       [ 6],
       [65],
       [23],
       [19],
       [ 8],
       [83],
       [59],
       [69],
       [64],
       [50],
       [ 5],
       [72],
       [34],
       [13],
       [51],
       [33],
       [75],
       [16],
       [10],
       [34],
       [38],
       [14],
       [27],
       [54],
       [19],
       [51],
       [23],
       [20],
       [46],
       [31],
       [82],
       [71],
       [38],
       [80],
       [14],
       [19],
       [74],
       [42],
       [60],
       [80],
       [12],
       [71],
       [70],
       [69],
       [47],
       [24],
       [68],
       [26],
       [18],
       [22],
       [82],

In [99]:
x_test_age = x_test.drop(columns = ['gender','fever','cough','city']).values

In [100]:
x_test_age

array([[19],
       [79],
       [11],
       [42],
       [27],
       [82],
       [69],
       [83],
       [65],
       [49],
       [24],
       [34],
       [81],
       [56],
       [64],
       [83],
       [73],
       [20],
       [51],
       [40]])

Now that we processed all the columns INDIVIDUALLY , we will concatenate them

In [101]:
x_train_transform = np.concatenate((x_train_age ,x_train_city,x_train_cough,x_train_fever,x_train_gender),axis=1)

In [102]:
x_train_transform

array([[ 10.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.        ,   1.        ],
       [ 55.        ,   0.        ,   1.        ,   0.        ,
          0.        , 100.        ,   1.        ],
       [ 17.        ,   0.        ,   1.        ,   0.        ,
          0.        , 104.        ,   0.        ],
       [ 44.        ,   0.        ,   0.        ,   1.        ,
          0.        , 104.        ,   1.        ],
       [ 11.        ,   0.        ,   1.        ,   0.        ,
          1.        , 100.        ,   0.        ],
       [ 65.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   1.        ],
       [ 75.        ,   1.        ,   0.        ,   0.        ,
          1.        , 104.        ,   0.        ],
       [  5.        ,   0.        ,   1.        ,   0.        ,
          0.        , 102.        ,   1.        ],
       [ 34.        ,   1.        ,   0.        ,   0.        ,
          1.    

As we manually preprocessed the whole data (each column - individually), the order in train and test data MUST remains the same.

In [105]:
x_test_transform = np.concatenate((x_test_age ,x_test_city,x_test_cough,x_test_fever, x_test_gender),axis = 1)

In [106]:
x_test_transform

array([[ 19.        ,   1.        ,   0.        ,   0.        ,
          0.        , 101.        ,   1.        ],
       [ 79.        ,   0.        ,   1.        ,   0.        ,
          1.        , 100.66666667,   1.        ],
       [ 11.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.        ,   1.        ],
       [ 42.        ,   0.        ,   0.        ,   1.        ,
          0.        , 104.        ,   1.        ],
       [ 27.        ,   1.        ,   0.        ,   0.        ,
          0.        , 100.        ,   1.        ],
       [ 82.        ,   0.        ,   1.        ,   0.        ,
          1.        , 102.        ,   0.        ],
       [ 69.        ,   0.        ,   1.        ,   0.        ,
          0.        , 103.        ,   0.        ],
       [ 83.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  98.        ,   1.        ],
       [ 65.        ,   1.        ,   0.        ,   0.        ,
          0.    

In [112]:
x_train_transform.shape   

(80, 7)

In [111]:
x_test_transform.shape

(20, 7)

In [113]:
x_train_transform.shape[1] == x_test_transform.shape[1]

True

NOW USING COLUMN TRANSFORMER CLASS

In [114]:
from sklearn.compose import ColumnTransformer

In [116]:
ct = ColumnTransformer(transformers=[

    ('t1',SimpleImputer() , ['fever']),
    ('t2',OrdinalEncoder(categories=[['Mild','Strong']]) ,['cough']),
    ('t3',OneHotEncoder(sparse_output=False ,drop='first') ,['gender','city'])
],remainder='passthrough')

In [118]:
x_train_transformer_transformed = ct.fit_transform(x_train)

In [119]:
x_train_transformer_transformed.shape

(80, 7)

In [120]:
x_test_transformer_transformed = ct.fit_transform(x_test)

In [121]:
x_test_transformer_transformed.shape

(20, 7)