In [27]:
import pickle 

In [28]:
import numpy as np

In [29]:
ohe_sex = pickle.load(open('ohe_sex.pkl' ,'rb'))

In [30]:
ohe_embarked = pickle.load(open('ohe_embarked.pkl' , 'rb'))

In [31]:
clf = pickle.load(open('clf.pkl' , 'rb'))

In [32]:
new_test_input = np.array([2,'male' , 31.0  , 0,0,10.5, 'S'] ,dtype=object).reshape(1,7)

In [33]:
new_test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [34]:
new_test_input_sex = ohe_sex.transform(new_test_input[:,1].reshape(1,1))

c:\Users\OM\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
new_test_input_sex

array([[0., 1.]])

In [36]:
new_test_input_embarked = ohe_embarked.transform(new_test_input[:,-1].reshape(1,1))

In [37]:
new_test_input_sex

array([[0., 1.]])

In [38]:
new_test_input_embarked

array([[0., 0., 1.]])

In [39]:
new_test_input_age = new_test_input[:,2].reshape(1,1)

In [40]:
new_test_input_transformed = np.concatenate((new_test_input[:,[0,3,4,5 ]] ,new_test_input_age ,   new_test_input_sex , new_test_input_embarked) , axis = 1)

In [41]:
new_test_input_transformed.shape

(1, 10)

In [42]:
clf.predict(new_test_input_transformed)

array([1])