In [4]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2026-02-19 05:30:17--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.03s   

2026-02-19 05:30:18 (33.9 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [10]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [11]:
len(text)

1115394

Tokenization

In [12]:
text[:10]

'First Citi'

In [16]:
chars  = sorted(list(set(text)))

In [18]:
vocab_size = len(chars)
vocab_size

65

In [19]:
''.join(chars)

"\n !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

In [28]:
stoi ={ch:i for i , ch in enumerate(chars)}
stoi


{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [ ]:
itos = {i:ch for i ,ch  in enumerate(chars)}


In [27]:
itos

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [29]:
encode = lambda s : [stoi[c] for c in s ]

In [30]:
encode("Hii")

[20, 47, 47]

In [31]:
decode = lambda l : ''.join([itos[i] for i in l ])

In [33]:
decode([20,47,47])

'Hii'

It is the simplest way to do the tokenization. At character level.

In [ ]:
# import tiktoken
# e = tiktoken.get_encoding('gpt2')
# e.n_vocab
# e.encode("hii there")

# e.decode([71,4178,612])

'hii there'

Encoding the text/data with the encoder

In [40]:
import torch

In [41]:
data = torch.tensor(encode(text) ,dtype=torch.long)

In [42]:
data.shape

torch.Size([1115394])

In [45]:
data.dtype

torch.int64

In [44]:
text[:50]

'First Citizen:\nBefore we proceed any further, hear'

In [43]:
data[:50]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56])

Train test split

About 90% of the text as a training dataset and the rest as a test 

In [46]:
n = int(0.9 * len(data))

In [47]:
train_data = data[:n]

In [48]:
train_data.shape

torch.Size([1003854])

In [50]:
len(text)

1115394

In [49]:
len(train_data)

1003854

In [52]:
len(train_data) / len(data)

0.8999994620734916

In [53]:
test_data = data[n:]

In [55]:
len(test_data)

111540

In [56]:
test_data.shape

torch.Size([111540])

In [57]:
len(test_data) / len(data)

0.10000053792650848

Instead of training model on entire dataset at once (Which is computationally expensive!) , here we are training on 'block_size' chunks.
The block_size can be any random size, here we are starting with 8.

In [68]:
block_size = 8 

In [69]:
train_data[:block_size + 1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

What does the above code does is : In context of 18 the very likely next character is 47. 
Similarly, for 18,47 the next very likely character is 56 and so on and so forth.

In [77]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print(f'{context} : {target}')

tensor([18]) : 47
tensor([18, 47]) : 56
tensor([18, 47, 56]) : 57
tensor([18, 47, 56, 57]) : 58
tensor([18, 47, 56, 57, 58]) : 1
tensor([18, 47, 56, 57, 58,  1]) : 15
tensor([18, 47, 56, 57, 58,  1, 15]) : 47
tensor([18, 47, 56, 57, 58,  1, 15, 47]) : 58


The above code demonstrates how to prepare input x and target y sequences for training a character-level language model using PyTorch tensors.

This is the length of the context window, set to 8. It determines how many previous characters the model will use to predict the next character.

This tensor contains a sequence of integers representing the encoded characters from the training data, specifically the first block_size characters.

This tensor contains the next character for each position in x, and it is shifted by one position relative to x. For every character in x, the corresponding value in y is the character that follows it in the text.
  
By using a context window or block_size, we train the model to predict the next character given a sequence of previous characters. This approach is computationally efficient and helps the model learn dependencies in the text without processing the entire dataset at once.

Although, it is a one example of a single batch training, the true power of tensors is the parallel processing which is completely independent of each other and trains the model effectively in parallel making the process faster.

In [78]:
x

tensor([18, 47, 56, 57, 58,  1, 15, 47])

In [80]:
y

tensor([47, 56, 57, 58,  1, 15, 47, 58])

Now Training the model in the batches - parallel processing 